### PR TITLE
Upgrade playdate-sys

### PR DESCRIPTION
**Pull request by paulyoung**

### CODE REVIEW

**Comment by jcornaz** [comment]
Hi :wave: 

Thank you so much for your contribution :pray: 

Unfortunately, I don't know why the build suddenly broke the main branch, and I don't have the time to investigate any further. 

If you have an idea of how to fix the build, or if you somehow manage to fix it, that'd be awesome :smile_cat: .

**Comment by paulyoung** [comment]
Hi @jcornaz. I was really just trying this out after @boozook mentioned it to me.

Although I got things working after the upgrade I wasn't planning on using it any further, but wanted to try and be helpful and contribute the changes I'd already made.

Unfortunately I probably won't be able to look into the build failure any time soon either.

**Comment by jcornaz** [comment]
No problem. Thanks for your contribution so far :100:

**Comment by boozook** [comment]
I'll look into this in some near future.

**Comment by jcornaz** [comment]
> I'll look into this in some near future.

Thanks @boozook.

I eventually managed to fix the build on main, and I released version `0.2.0` of `crankit-game-loop`.

**Pull request closed without merging**
